### PR TITLE
rename device to mis-focus-controller

### PR DESCRIPTION
**Pull request by chronopoulos**
did this in 3 places: hardware, firmware, and software. had to be careful since there were a couple different names in use throughout the repo: cafomoco, multicam_focus, multicamfocusrig, etc. I'd like to converge on one name for this device, "mis-focus-controller" and use that throughout the various subdirectories.

i've tested the examples in software but not the firmware rebuild, which i assume is trivial since it's only a project name in the CMakeLists.txt

### CODE REVIEW

**Comment by chronopoulos** [comment]
have you gotten a chance to review this?

**Comment by Poofjunior** [comment]
Let's un-add the kicad_pcb file, and then I'll bring in everything else. (I have the name updated in another branch, which I can submit right after.)

**Comment by chronopoulos** [comment]
> Let's un-add the kicad_pcb file, and then I'll bring in everything else. (I have the name updated in another branch, which I can submit right after.)

Can you handle this? Either do a merge commit which chooses your kicad_pcb over mine. Or else bring my changes into your branch, or whatever. Or revert the kicad_pcb on this branch (which you should have permissions for). But let's just get this updated.

**Comment by Poofjunior** [comment]
Ok, I checked out the main branches .kicad_sch and .kicad_pcb files into this branch. This should be mergeable now.

**Pull request merged**
